# render.yaml
# Este archivo le dice a Render cómo construir y desplegar tu aplicación y base de datos.
# https://render.com/docs/blueprint-spec

databases:
  # Define la base de datos PostgreSQL.
  - name: futbol5-db
    databaseName: futbol5_db # Nombre interno de la base de datos
    user: futbol5_user      # Nombre de usuario para la base de datos
    plan: free              # Usa el plan gratuito

services:
  # Define el servicio web para tu aplicación Flask.
  - type: web
    name: futbol5-app
    runtime: python
    plan: free
    # Comando para construir el servicio: instala dependencias y ejecuta migraciones.
    buildCommand: "pip install -r requirements.txt; flask db upgrade"
    # Comando para iniciar el servicio.
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12 # Basado en tu entorno local
      - key: DATABASE_URL
        fromDatabase:
          name: futbol5-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render generará una clave segura automáticamente
