"""Agregar modelo Partido y relacion de inscripciones

Revision ID: 18d6a6947b51
Revises: 2c437e6b99ee
Create Date: 2025-08-20 11:39:37.256122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d6a6947b51'
down_revision = '2c437e6b99ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('jugadores_necesarios', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('jugador_id', 'partido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripciones')
    op.drop_table('partido')
    # ### end Alembic commands ###
