"""Initial migration.

Revision ID: 2c437e6b99ee
Revises: 
Create Date: 2025-08-20 11:18:49.038269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c437e6b99ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('puntaje_global', sa.Float(), nullable=True),
    sa.Column('puntaje_ataque', sa.Float(), nullable=True),
    sa.Column('puntaje_defensa', sa.Float(), nullable=True),
    sa.Column('puntaje_fisico', sa.Float(), nullable=True),
    sa.Column('puntaje_pases', sa.Float(), nullable=True),
    sa.Column('puntaje_vision', sa.Float(), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jugador')
    # ### end Alembic commands ###
