"""Agregar tabla calificacion

Revision ID: 5396abf0f755
Revises: d8ce7b63ace8
Create Date: 2025-08-20 16:16:06.455104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5396abf0f755'
down_revision = 'd8ce7b63ace8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calificador_id', sa.Integer(), nullable=False),
    sa.Column('calificado_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('ataque', sa.Float(), nullable=False),
    sa.Column('defensa', sa.Float(), nullable=False),
    sa.Column('fisico', sa.Float(), nullable=False),
    sa.Column('pases', sa.Float(), nullable=False),
    sa.Column('vision', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['calificado_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['calificador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calificador_id', 'calificado_id', 'partido_id', name='_calificacion_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificacion')
    # ### end Alembic commands ###
