"""Creacion inicial de la base de datos

Revision ID: 5b4830860b7c
Revises: 
Create Date: 2025-08-20 14:37:49.122267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4830860b7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('puntaje_global', sa.Float(), nullable=True),
    sa.Column('puntaje_ataque', sa.Float(), nullable=True),
    sa.Column('puntaje_defensa', sa.Float(), nullable=True),
    sa.Column('puntaje_fisico', sa.Float(), nullable=True),
    sa.Column('puntaje_pases', sa.Float(), nullable=True),
    sa.Column('puntaje_vision', sa.Float(), nullable=True),
    sa.Column('partidos_jugados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('jugadores_necesarios', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscripciones',
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugador.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('jugador_id', 'partido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripciones')
    op.drop_table('partido')
    op.drop_table('jugador')
    # ### end Alembic commands ###
