"""Agregar autenticacion a Jugador

Revision ID: 8d4162e2cfa1
Revises: 18d6a6947b51
Create Date: 2025-08-20 14:06:12.352100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4162e2cfa1'
down_revision = '18d6a6947b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
